### ISSUE TITLE
C8 Capacitor Clock Module

### ISSUE THREAD

**Issue by davrad3** [tebl/BE6502-Build-a-65c02-computer#3]
Hello,
thank you for this amazing project.
I had the pcb produced and now I am wondering why the 4 pins of SW1 are connected to each other and why the capacitor C8 is connected to GND with both pins.
Thank you so much

**Comment by tebl** [comment]
This appears to have been one of my mistakes, sorry about that. I've added some details to the errata section of the README, can you check that out and see if that fixes the issue. Cutting the track under C8 should stop all of the pins under SW1 from appearing shorted.

https://github.com/tebl/BE6502-Build-a-65c02-computer#errata
https://github.com/tebl/BE6502-Build-a-65c02-computer/blob/master/gallery/Screenshot%202021-11-30%20194604.png

**Comment by davrad3** [comment]
Thank you very much!
